spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8mb4&connectionCollation=utf8mb4_general_ci&serverTimezone=Asia/Seoul
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  jackson:
    time-zone: Asia/Seoul

  devtools:
    restart:
      enabled: false

logging:
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
    com.example.backend.auth: DEBUG
    com.google.firebase: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

firebase:
  credentials:
    resource: classpath:gdg-team3-firebase-adminsdk-fbsvc-56fc83e392.json
  project-id: gdg-team3

auth:
  allowed-email-domains:
    - seoultech.ac.kr
    - g.seoultech.ac.kr
